/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RetreatsRouteImport } from './routes/retreats'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as CorporateRouteImport } from './routes/corporate'
import { Route as BookRouteImport } from './routes/book'
import { Route as ApproachRouteImport } from './routes/approach'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ActivitiesRouteImport } from './routes/activities'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RetreatsIndexRouteImport } from './routes/retreats.index'
import { Route as ResourcesIndexRouteImport } from './routes/resources.index'
import { Route as ExpertsIndexRouteImport } from './routes/experts.index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as RetreatsSlugRouteImport } from './routes/retreats.$slug'
import { Route as ResourcesTestsRouteImport } from './routes/resources.tests'
import { Route as ResourcesCreativeCreationsRouteImport } from './routes/resources.creative-creations'
import { Route as ResourcesSlugRouteImport } from './routes/resources.$slug'
import { Route as ExpertsSlugRouteImport } from './routes/experts.$slug'
import { Route as ApiCollectRouteImport } from './routes/api/collect'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminInboxRouteImport } from './routes/admin.inbox'
import { Route as AdminContactsRouteImport } from './routes/admin.contacts'
import { Route as AdminCalendarRouteImport } from './routes/admin.calendar'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as ResourcesTestsIndexRouteImport } from './routes/resources.tests.index'
import { Route as ResourcesTestsSlugRouteImport } from './routes/resources.tests.$slug'

const RetreatsRoute = RetreatsRouteImport.update({
  id: '/retreats',
  path: '/retreats',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const CorporateRoute = CorporateRouteImport.update({
  id: '/corporate',
  path: '/corporate',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const ApproachRoute = ApproachRouteImport.update({
  id: '/approach',
  path: '/approach',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivitiesRoute = ActivitiesRouteImport.update({
  id: '/activities',
  path: '/activities',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RetreatsIndexRoute = RetreatsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RetreatsRoute,
} as any)
const ResourcesIndexRoute = ResourcesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ResourcesRoute,
} as any)
const ExpertsIndexRoute = ExpertsIndexRouteImport.update({
  id: '/experts/',
  path: '/experts/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const RetreatsSlugRoute = RetreatsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => RetreatsRoute,
} as any)
const ResourcesTestsRoute = ResourcesTestsRouteImport.update({
  id: '/tests',
  path: '/tests',
  getParentRoute: () => ResourcesRoute,
} as any)
const ResourcesCreativeCreationsRoute =
  ResourcesCreativeCreationsRouteImport.update({
    id: '/creative-creations',
    path: '/creative-creations',
    getParentRoute: () => ResourcesRoute,
  } as any)
const ResourcesSlugRoute = ResourcesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ResourcesRoute,
} as any)
const ExpertsSlugRoute = ExpertsSlugRouteImport.update({
  id: '/experts/$slug',
  path: '/experts/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCollectRoute = ApiCollectRouteImport.update({
  id: '/api/collect',
  path: '/api/collect',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInboxRoute = AdminInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContactsRoute = AdminContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCalendarRoute = AdminCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const ResourcesTestsIndexRoute = ResourcesTestsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ResourcesTestsRoute,
} as any)
const ResourcesTestsSlugRoute = ResourcesTestsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ResourcesTestsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activities': typeof ActivitiesRoute
  '/admin': typeof AdminRouteWithChildren
  '/approach': typeof ApproachRoute
  '/book': typeof BookRoute
  '/corporate': typeof CorporateRoute
  '/resources': typeof ResourcesRouteWithChildren
  '/retreats': typeof RetreatsRouteWithChildren
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/calendar': typeof AdminCalendarRoute
  '/admin/contacts': typeof AdminContactsRoute
  '/admin/inbox': typeof AdminInboxRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/api/chat': typeof ApiChatRoute
  '/api/collect': typeof ApiCollectRoute
  '/experts/$slug': typeof ExpertsSlugRoute
  '/resources/$slug': typeof ResourcesSlugRoute
  '/resources/creative-creations': typeof ResourcesCreativeCreationsRoute
  '/resources/tests': typeof ResourcesTestsRouteWithChildren
  '/retreats/$slug': typeof RetreatsSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/experts/': typeof ExpertsIndexRoute
  '/resources/': typeof ResourcesIndexRoute
  '/retreats/': typeof RetreatsIndexRoute
  '/resources/tests/$slug': typeof ResourcesTestsSlugRoute
  '/resources/tests/': typeof ResourcesTestsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activities': typeof ActivitiesRoute
  '/approach': typeof ApproachRoute
  '/book': typeof BookRoute
  '/corporate': typeof CorporateRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/calendar': typeof AdminCalendarRoute
  '/admin/contacts': typeof AdminContactsRoute
  '/admin/inbox': typeof AdminInboxRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/api/chat': typeof ApiChatRoute
  '/api/collect': typeof ApiCollectRoute
  '/experts/$slug': typeof ExpertsSlugRoute
  '/resources/$slug': typeof ResourcesSlugRoute
  '/resources/creative-creations': typeof ResourcesCreativeCreationsRoute
  '/retreats/$slug': typeof RetreatsSlugRoute
  '/admin': typeof AdminIndexRoute
  '/experts': typeof ExpertsIndexRoute
  '/resources': typeof ResourcesIndexRoute
  '/retreats': typeof RetreatsIndexRoute
  '/resources/tests/$slug': typeof ResourcesTestsSlugRoute
  '/resources/tests': typeof ResourcesTestsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activities': typeof ActivitiesRoute
  '/admin': typeof AdminRouteWithChildren
  '/approach': typeof ApproachRoute
  '/book': typeof BookRoute
  '/corporate': typeof CorporateRoute
  '/resources': typeof ResourcesRouteWithChildren
  '/retreats': typeof RetreatsRouteWithChildren
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/calendar': typeof AdminCalendarRoute
  '/admin/contacts': typeof AdminContactsRoute
  '/admin/inbox': typeof AdminInboxRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/api/chat': typeof ApiChatRoute
  '/api/collect': typeof ApiCollectRoute
  '/experts/$slug': typeof ExpertsSlugRoute
  '/resources/$slug': typeof ResourcesSlugRoute
  '/resources/creative-creations': typeof ResourcesCreativeCreationsRoute
  '/resources/tests': typeof ResourcesTestsRouteWithChildren
  '/retreats/$slug': typeof RetreatsSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/experts/': typeof ExpertsIndexRoute
  '/resources/': typeof ResourcesIndexRoute
  '/retreats/': typeof RetreatsIndexRoute
  '/resources/tests/$slug': typeof ResourcesTestsSlugRoute
  '/resources/tests/': typeof ResourcesTestsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activities'
    | '/admin'
    | '/approach'
    | '/book'
    | '/corporate'
    | '/resources'
    | '/retreats'
    | '/admin/analytics'
    | '/admin/calendar'
    | '/admin/contacts'
    | '/admin/inbox'
    | '/admin/settings'
    | '/api/chat'
    | '/api/collect'
    | '/experts/$slug'
    | '/resources/$slug'
    | '/resources/creative-creations'
    | '/resources/tests'
    | '/retreats/$slug'
    | '/admin/'
    | '/experts/'
    | '/resources/'
    | '/retreats/'
    | '/resources/tests/$slug'
    | '/resources/tests/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activities'
    | '/approach'
    | '/book'
    | '/corporate'
    | '/admin/analytics'
    | '/admin/calendar'
    | '/admin/contacts'
    | '/admin/inbox'
    | '/admin/settings'
    | '/api/chat'
    | '/api/collect'
    | '/experts/$slug'
    | '/resources/$slug'
    | '/resources/creative-creations'
    | '/retreats/$slug'
    | '/admin'
    | '/experts'
    | '/resources'
    | '/retreats'
    | '/resources/tests/$slug'
    | '/resources/tests'
  id:
    | '__root__'
    | '/'
    | '/activities'
    | '/admin'
    | '/approach'
    | '/book'
    | '/corporate'
    | '/resources'
    | '/retreats'
    | '/admin/analytics'
    | '/admin/calendar'
    | '/admin/contacts'
    | '/admin/inbox'
    | '/admin/settings'
    | '/api/chat'
    | '/api/collect'
    | '/experts/$slug'
    | '/resources/$slug'
    | '/resources/creative-creations'
    | '/resources/tests'
    | '/retreats/$slug'
    | '/admin/'
    | '/experts/'
    | '/resources/'
    | '/retreats/'
    | '/resources/tests/$slug'
    | '/resources/tests/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivitiesRoute: typeof ActivitiesRoute
  AdminRoute: typeof AdminRouteWithChildren
  ApproachRoute: typeof ApproachRoute
  BookRoute: typeof BookRoute
  CorporateRoute: typeof CorporateRoute
  ResourcesRoute: typeof ResourcesRouteWithChildren
  RetreatsRoute: typeof RetreatsRouteWithChildren
  ApiChatRoute: typeof ApiChatRoute
  ApiCollectRoute: typeof ApiCollectRoute
  ExpertsSlugRoute: typeof ExpertsSlugRoute
  ExpertsIndexRoute: typeof ExpertsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/retreats': {
      id: '/retreats'
      path: '/retreats'
      fullPath: '/retreats'
      preLoaderRoute: typeof RetreatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/corporate': {
      id: '/corporate'
      path: '/corporate'
      fullPath: '/corporate'
      preLoaderRoute: typeof CorporateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approach': {
      id: '/approach'
      path: '/approach'
      fullPath: '/approach'
      preLoaderRoute: typeof ApproachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activities': {
      id: '/activities'
      path: '/activities'
      fullPath: '/activities'
      preLoaderRoute: typeof ActivitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/retreats/': {
      id: '/retreats/'
      path: '/'
      fullPath: '/retreats/'
      preLoaderRoute: typeof RetreatsIndexRouteImport
      parentRoute: typeof RetreatsRoute
    }
    '/resources/': {
      id: '/resources/'
      path: '/'
      fullPath: '/resources/'
      preLoaderRoute: typeof ResourcesIndexRouteImport
      parentRoute: typeof ResourcesRoute
    }
    '/experts/': {
      id: '/experts/'
      path: '/experts'
      fullPath: '/experts/'
      preLoaderRoute: typeof ExpertsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/retreats/$slug': {
      id: '/retreats/$slug'
      path: '/$slug'
      fullPath: '/retreats/$slug'
      preLoaderRoute: typeof RetreatsSlugRouteImport
      parentRoute: typeof RetreatsRoute
    }
    '/resources/tests': {
      id: '/resources/tests'
      path: '/tests'
      fullPath: '/resources/tests'
      preLoaderRoute: typeof ResourcesTestsRouteImport
      parentRoute: typeof ResourcesRoute
    }
    '/resources/creative-creations': {
      id: '/resources/creative-creations'
      path: '/creative-creations'
      fullPath: '/resources/creative-creations'
      preLoaderRoute: typeof ResourcesCreativeCreationsRouteImport
      parentRoute: typeof ResourcesRoute
    }
    '/resources/$slug': {
      id: '/resources/$slug'
      path: '/$slug'
      fullPath: '/resources/$slug'
      preLoaderRoute: typeof ResourcesSlugRouteImport
      parentRoute: typeof ResourcesRoute
    }
    '/experts/$slug': {
      id: '/experts/$slug'
      path: '/experts/$slug'
      fullPath: '/experts/$slug'
      preLoaderRoute: typeof ExpertsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/collect': {
      id: '/api/collect'
      path: '/api/collect'
      fullPath: '/api/collect'
      preLoaderRoute: typeof ApiCollectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/inbox': {
      id: '/admin/inbox'
      path: '/inbox'
      fullPath: '/admin/inbox'
      preLoaderRoute: typeof AdminInboxRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/contacts': {
      id: '/admin/contacts'
      path: '/contacts'
      fullPath: '/admin/contacts'
      preLoaderRoute: typeof AdminContactsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/calendar': {
      id: '/admin/calendar'
      path: '/calendar'
      fullPath: '/admin/calendar'
      preLoaderRoute: typeof AdminCalendarRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/resources/tests/': {
      id: '/resources/tests/'
      path: '/'
      fullPath: '/resources/tests/'
      preLoaderRoute: typeof ResourcesTestsIndexRouteImport
      parentRoute: typeof ResourcesTestsRoute
    }
    '/resources/tests/$slug': {
      id: '/resources/tests/$slug'
      path: '/$slug'
      fullPath: '/resources/tests/$slug'
      preLoaderRoute: typeof ResourcesTestsSlugRouteImport
      parentRoute: typeof ResourcesTestsRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminCalendarRoute: typeof AdminCalendarRoute
  AdminContactsRoute: typeof AdminContactsRoute
  AdminInboxRoute: typeof AdminInboxRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminCalendarRoute: AdminCalendarRoute,
  AdminContactsRoute: AdminContactsRoute,
  AdminInboxRoute: AdminInboxRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ResourcesTestsRouteChildren {
  ResourcesTestsSlugRoute: typeof ResourcesTestsSlugRoute
  ResourcesTestsIndexRoute: typeof ResourcesTestsIndexRoute
}

const ResourcesTestsRouteChildren: ResourcesTestsRouteChildren = {
  ResourcesTestsSlugRoute: ResourcesTestsSlugRoute,
  ResourcesTestsIndexRoute: ResourcesTestsIndexRoute,
}

const ResourcesTestsRouteWithChildren = ResourcesTestsRoute._addFileChildren(
  ResourcesTestsRouteChildren,
)

interface ResourcesRouteChildren {
  ResourcesSlugRoute: typeof ResourcesSlugRoute
  ResourcesCreativeCreationsRoute: typeof ResourcesCreativeCreationsRoute
  ResourcesTestsRoute: typeof ResourcesTestsRouteWithChildren
  ResourcesIndexRoute: typeof ResourcesIndexRoute
}

const ResourcesRouteChildren: ResourcesRouteChildren = {
  ResourcesSlugRoute: ResourcesSlugRoute,
  ResourcesCreativeCreationsRoute: ResourcesCreativeCreationsRoute,
  ResourcesTestsRoute: ResourcesTestsRouteWithChildren,
  ResourcesIndexRoute: ResourcesIndexRoute,
}

const ResourcesRouteWithChildren = ResourcesRoute._addFileChildren(
  ResourcesRouteChildren,
)

interface RetreatsRouteChildren {
  RetreatsSlugRoute: typeof RetreatsSlugRoute
  RetreatsIndexRoute: typeof RetreatsIndexRoute
}

const RetreatsRouteChildren: RetreatsRouteChildren = {
  RetreatsSlugRoute: RetreatsSlugRoute,
  RetreatsIndexRoute: RetreatsIndexRoute,
}

const RetreatsRouteWithChildren = RetreatsRoute._addFileChildren(
  RetreatsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivitiesRoute: ActivitiesRoute,
  AdminRoute: AdminRouteWithChildren,
  ApproachRoute: ApproachRoute,
  BookRoute: BookRoute,
  CorporateRoute: CorporateRoute,
  ResourcesRoute: ResourcesRouteWithChildren,
  RetreatsRoute: RetreatsRouteWithChildren,
  ApiChatRoute: ApiChatRoute,
  ApiCollectRoute: ApiCollectRoute,
  ExpertsSlugRoute: ExpertsSlugRoute,
  ExpertsIndexRoute: ExpertsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
